##############################
# - Note Block Melody        #
# - Created By MineStar Team #
# - www.Minestar.top         #
##############################
#
# join discord for download config for all version
# https://discord.gg/R9YCwtzGmy
#
# NoteBlockMelody Made by :
# Amirreza83
# XserGod
# Moftbar_Diamond
# Mahshid_
#
##############################

craftable: true